apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: d7euqeruq-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/d7euqeruq-java-springboot-gitops